// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseInvoiceSystem.Infrastructure.Data;

#nullable disable

namespace WarehouseInvoiceSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317130000_AddTenantTable")]
    partial class AddTenantTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseInvoiceSystem.Domain.Entities.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CompanyName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("EmailPasswordEncrypted")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<byte[]>("LogoData")
                    .HasColumnType("bytea");

                b.Property<string>("LogoMimeType")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("OperatorName")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Address")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Phone")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("Website")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("Tenant", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}