namespace WarehouseInvoiceSystem.Application.Services
{
    using System.Globalization;
    using WarehouseInvoiceSystem.Application.Interfaces;

    public class LocalizationService : ILocalizationService
    {
        private string _currentLanguage = "mk";

        public string CurrentLanguage => _currentLanguage;

        public event Action? OnLanguageChanged;

        private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            #region English translations
            ["en"] = new Dictionary<string, string>
            {
                // Navigation
                ["Dashboard"] = "Dashboard",
                ["Companies"] = "Companies",
                ["Invoices"] = "Invoices",
                ["Payments"] = "Payments",
                ["Settings"] = "Settings",
                ["Notifications"] = "Notifications",

                // Dashboard
                ["TotalDue"] = "Total Due",
                ["TotalInvoices"] = "Total Invoices",
                ["Overdue"] = "Overdue",
                ["TotalPaid"] = "Total Paid",
                ["InvoicesUnpaid"] = "invoices unpaid",
                ["Paid"] = "paid",
                ["RequiresAttention"] = "Requires attention",
                ["AllTimeCollected"] = "All time collected",
                ["RecentInvoices"] = "Recent Invoices",
                ["NewInvoice"] = "New Invoice",
                ["NoInvoicesFound"] = "No invoices found",
                ["InvoiceNumber"] = "Invoice #",
                ["Company"] = "Company",
                ["Amount"] = "Amount",
                ["Status"] = "Status",
                ["DueDate"] = "Due Date",
                ["Actions"] = "Actions",
                ["ViewAllInvoices"] = "View All Invoices",

                // Status
                ["Draft"] = "Draft",
                ["Sent"] = "Sent",
                ["PartiallyPaid"] = "Partially Paid",
                ["Paid"] = "Paid",
                ["OverdueStatus"] = "Overdue",
                ["CancelledStatus"] = "Cancelled",

                // Common
                ["Loading"] = "Loading...",
                ["Saving"] = "Saving...",
                ["Save"] = "Save",
                ["Cancel"] = "Cancel",
                ["Delete"] = "Delete",
                ["Edit"] = "Edit",
                ["View"] = "View",
                ["Create"] = "Create",
                ["Update"] = "Update",
                ["Search"] = "Search",
                ["Filter"] = "Filter",
                ["Export"] = "Export",
                ["Import"] = "Import",
                ["InvoiceSystem"] = "Invoice System",
                ["Help"] = "Help",
                ["Privacy"] = "Privacy",
                ["Terms"] = "Terms",
                ["Brajkovci"] = "Brajkovci, Valandovo, Makedonija",
                ["ThankYou"] = "Thank you for your business!",
                ["AdvancedFilters"] = "Advanced Filters",
                ["AmountRange"] = "Amount Range",
                ["Min"] = "Min",
                ["Max"] = "Max",
                ["From"] = "From",
                ["To"] = "To",
                ["ClearFilters"] = "Clear Filters",
                ["NoItemsFound"] = "No items found",
                ["Previous"] = "Previous",
                ["Next"] = "Next",
                ["Page"] = "Page",
                ["Of"] = "of",
                ["ItemsPerPage"] = "Items per page:",

                // Email
                ["SendInvoice"] = "Send Invoice",
                ["SendEmail"] = "Send Email",
                ["EmailSent"] = "Email sent successfully",
                ["SendingEmail"] = "Sending email...",
                ["EnterCustomMessage"] = "Enter a custom message to include in the email",
                ["EmailWillBeSent"] = "The invoice will be sent as an attachment and the status will be updated to 'Sent'",

                // Companies
                ["AllCompanies"] = "All Companies",
                ["Clients"] = "Clients",
                ["Vendors"] = "Vendors",
                ["CreateCompany"] = "Create Company",
                ["EditCompany"] = "Edit Company",
                ["CompanyDetails"] = "Company Details",
                ["BackToCompanies"] = "Back to Companies",
                ["ContactPerson"] = "Contact Person",
                ["Email"] = "Email",
                ["Phone"] = "Phone",
                ["Address"] = "Address",
                ["TaxID"] = "Tax ID",
                ["CreditLimit"] = "Credit Limit",
                ["Active"] = "Active",
                ["Inactive"] = "Inactive",
                ["Client"] = "Client",
                ["Vendor"] = "Vendor",
                ["ClientAndVendor"] = "Client & Vendor",
                ["SelectCompanyType"] = "Select company type",
                ["EnterCompanyName"] = "Enter company name",
                ["EnterContactPerson"] = "Enter contact person",
                ["EnterEmail"] = "Enter email address",
                ["EnterPhone"] = "Enter phone number",
                ["EnterAddress"] = "Enter full address",
                ["EnterTaxID"] = "Enter tax ID",
                ["EnterCreditLimit"] = "Enter credit limit",
                ["CompanyName"] = "Company Name",
                ["CompanyType"] = "Company Type",
                ["CompanyCreated"] = "Company created successfully",
                ["CompanyUpdated"] = "Company updated successfully",
                ["CompanyDeleted"] = "Company deleted successfully",
                ["ErrorLoadingCompany"] = "Error loading company",
                ["ErrorCreatingCompany"] = "Error creating company",
                ["ErrorUpdatingCompany"] = "Error updating company",
                ["ErrorDeletingCompany"] = "Error deleting company",
                ["DeleteCompanyConfirm"] = "Are you sure you want to delete this company? This action cannot be undone.",
                ["PleaseEnterCompanyName"] = "Please enter company name",
                ["PleaseEnterCompanyType"] = "Please enter company type",
                ["BalanceOwed"] = "Balance Owed",
                ["WeOwe"] = "We Owe",
                ["TheyOwe"] = "They Owe Us",
                ["NetBalance"] = "Net Balance",
                ["ViewInvoices"] = "View Invoices",
                ["TotalInvoicesCount"] = "Total Invoices",
                ["Settled"] = "Settled",
                ["ChooseCompanyType"] = "Choose company type",

                // Invoices
                ["Invoice"] = "Invoice",
                ["CreateInvoice"] = "Create Invoice",
                ["EditInvoice"] = "Edit Invoice",
                ["InvoiceDetails"] = "Invoice Details",
                ["AllInvoices"] = "All Invoices",
                ["Receivables"] = "Receivables",
                ["Payables"] = "Payables",
                ["Type"] = "Type",
                ["IssueDate"] = "Issue Date",
                ["Notes"] = "Notes",
                ["LineItems"] = "Line Items",
                ["Description"] = "Description",
                ["Quantity"] = "Quantity",
                ["UnitPrice"] = "Unit Price",
                ["TaxRate"] = "Tax Rate",
                ["Total"] = "Total",
                ["Subtotal"] = "Subtotal",
                ["Tax"] = "Tax",
                ["AmountPaid"] = "Amount Paid",
                ["AmountDue"] = "Amount Due",
                ["AddLineItem"] = "Add Line Item",
                ["RemoveLineItem"] = "Remove",
                ["BillTo"] = "Bill To",
                ["BillFrom"] = "Bill From",
                ["InvoiceInformation"] = "Invoice Information",
                ["PaymentHistory"] = "Payment History",
                ["NoPaymentsRecorded"] = "No payments recorded yet",
                ["BackToInvoices"] = "Back to Invoices",
                ["SelectCompany"] = "Select Company",
                ["SelectType"] = "Select Type",
                ["Receivable"] = "Receivable",
                ["Payable"] = "Payable",
                ["ConfirmDelete"] = "Confirm Delete",
                ["DeleteInvoiceConfirm"] = "Are you sure you want to delete this invoice? This action cannot be undone.",
                ["InvoiceDeleted"] = "Invoice deleted successfully",
                ["InvoiceCreated"] = "Invoice created successfully",
                ["InvoiceUpdated"] = "Invoice updated successfully",
                ["ErrorLoadingInvoice"] = "Error loading invoice",
                ["ErrorCreatingInvoice"] = "Error creating invoice",
                ["ErrorUpdatingInvoice"] = "Error updating invoice",
                ["ErrorDeletingInvoice"] = "Error deleting invoice",
                ["PleaseAddLineItems"] = "Please add at least one line item",
                ["PleaseEnterDescriptionOrSelectProduct"] = "Please enter a description or select a product for each line item",
                ["IssueDateRequired"] = "Issue date is required",
                ["DueDateRequired"] = "Due date is required",
                ["StatusRequired"] = "Status is required",
                ["Yes"] = "Yes",
                ["No"] = "No",
                ["Close"] = "Close",
                ["PaymentDate"] = "Payment Date",
                ["PaymentAmount"] = "Payment Amount",
                ["PaymentMethod"] = "Payment Method",
                ["ReferenceNumber"] = "Reference Number",
                ["RecordedBy"] = "Recorded By",
                ["ShowingResults"] = "Showing {0} to {1} of {2} results",
                ["Days"] = "days",
                ["SelectInvoiceType"] = "Select Invoice Type",
                ["DaysFromIssue"] = "Days from issue date",
                ["CalculateDueDate"] = "Calculate Due Date",
                ["AddItem"] = "Add Item",
                ["RemoveItem"] = "Remove Item",
                ["Item"] = "Item",
                ["PleaseSelectCompany"] = "Please select a company",
                ["PleaseSelectType"] = "Please select invoice type",
                ["PleaseAddAtLeastOneLineItem"] = "Please add at least one line item",
                ["EnterDescription"] = "Enter description",
                ["EnterQuantity"] = "Enter quantity",
                ["EnterUnitPrice"] = "Enter unit price",
                ["EnterTaxRate"] = "Enter tax rate (%)",
                ["Bill"] = "Bill",
                ["SendEmail"] = "Send Invoice Email",
                ["SendInvoiceEmail"] = "Send Invoice via Email",
                ["RecipientEmail"] = "Recipient Email",
                ["EnterRecipientEmail"] = "Enter the recipient's email address",
                ["IncludeCustomMessage"] = "Include a custom message",
                ["CustomMessage"] = "Custom Message",
                ["CustomMessageHelper"] = "Optional: Add a personal note to include in the email",
                ["Sending"] = "Sending...",
                ["InvalidEmailFormat"] = "Please enter a valid email address",
                ["InvoiceEmailSentSuccessfully"] = "Invoice email sent successfully!",
                ["ErrorSendingEmail"] = "Error sending email",

                // Payments
                ["Cash"] = "Cash",
                ["Check"] = "Check",
                ["BankTransfer"] = "Bank Transfer",
                ["CreditCard"] = "Credit Card",
                ["DebitCard"] = "Debit Card",
                ["Other"] = "Other",
                ["AllPayments"] = "All Payments",
                ["CreatePayment"] = "Create Payment",
                ["RecordPayment"] = "Record Payment",
                ["PaymentDetails"] = "Payment Details",
                ["BackToPayments"] = "Back to Payments",
                ["SelectInvoice"] = "Select Invoice",
                ["SelectPaymentMethod"] = "Select payment method",
                ["PleaseSelectPaymentMethod"] = "Please select a payment method",
                ["PaymentDateRequired"] = "Payment date is required",
                ["EnterAmount"] = "Enter amount",
                ["EnterReferenceNumber"] = "Enter reference number",
                ["EnterNotes"] = "Enter notes",
                ["MaximumAmount"] = "Maximum amount",
                ["RemainingBalance"] = "Remaining Balance",
                ["InvoiceAmount"] = "Invoice Amount",
                ["AlreadyPaid"] = "Already Paid",
                ["PaymentExceedsBalance"] = "Payment amount exceeds remaining balance",
                ["PleaseSelectInvoice"] = "Please select an invoice",
                ["PleaseEnterAmount"] = "Please enter payment amount",
                ["PaymentCreated"] = "Payment recorded successfully",
                ["PaymentUpdated"] = "Payment updated successfully",
                ["PaymentDeleted"] = "Payment deleted successfully",
                ["ErrorLoadingPayment"] = "Error loading payment",
                ["ErrorCreatingPayment"] = "Error creating payment",
                ["ErrorUpdatingPayment"] = "Error updating payment",
                ["ErrorDeletingPayment"] = "Error deleting payment",
                ["DeletePaymentConfirm"] = "Are you sure you want to delete this payment? This will update the invoice balance.",
                ["EditPayment"] = "Edit Payment",
                ["NoPaymentsFound"] = "No payments found",
                ["CreatedAt"] = "Created at",
                ["Payment"] = "Payment",

                // Export
                ["ExportToExcel"] = "Export to Excel",
                ["ExportForPrinting"] = "Export for Printing",
                ["ExportAllInvoices"] = "Export All Invoices",
                ["ExportByDateRange"] = "Export by Date Range",
                ["StartDate"] = "Start Date",
                ["EndDate"] = "End Date",
                ["ExportInvoices"] = "Export Invoices",
                ["Exporting"] = "Exporting...",
                ["ExportSuccess"] = "File exported successfully",
                ["ExportError"] = "Error exporting file",

                // Products
                ["Products"] = "Products",
                ["Product"] = "Product",
                ["CreateProduct"] = "Create Product",
                ["EditProduct"] = "Edit Product",
                ["ProductDetails"] = "Product Details",
                ["ProductName"] = "Product Name",
                ["ProductCode"] = "Product Code",
                ["Code"] = "Code",
                ["DefaultPrice"] = "Default Price",
                ["Price"] = "Price",
                ["Unit"] = "Unit",
                ["UnitHelper"] = "e.g., pcs, kg, l, m",
                ["AllProducts"] = "All Products",
                ["NoProductsFound"] = "No products found",
                ["ViewStock"] = "View Stock",
                ["CodeRequired"] = "Product code is required",
                ["NameRequired"] = "Product name is required",
                ["UnitRequired"] = "Unit is required",
                ["PriceRequired"] = "Price is required",
                ["ProductCreated"] = "Product created successfully",
                ["ProductUpdated"] = "Product updated successfully",
                ["ProductDeleted"] = "Product deleted successfully",
                ["DeleteProductConfirm"] = "Are you sure you want to delete this product?",
                ["ErrorLoadingProduct"] = "Error loading product",
                ["ErrorLoadingProducts"] = "Error loading products",
                ["ErrorCreatingProduct"] = "Error creating product",
                ["ErrorUpdatingProduct"] = "Error updating product",
                ["ErrorDeletingProduct"] = "Error deleting product",
                ["ProductNotFound"] = "Product not found",
                ["CustomDescription"] = "Custom Description",
                ["OrEnterCustom"] = "Or enter custom description",
                ["SelectProduct"] = "Select Product",
                ["ActiveProducts"] = "Active",
                ["InactiveProducts"] = "Inactive",
                ["ProductActive"] = "Active",
                ["ProductInactive"] = "Inactive",

                // Inventory
                ["Inventory"] = "Inventory",
                ["Stock"] = "Stock",
                ["StockLevel"] = "Stock Level",
                ["AdjustStock"] = "Adjust Stock",
                ["Adjust"] = "Adjust",
                ["AdjustmentType"] = "Adjustment Type",
                ["IncreaseStock"] = "Increase",
                ["DecreaseStock"] = "Decrease",
                ["AdjustmentReason"] = "Reason",
                ["StockAdjusted"] = "Stock adjusted successfully",
                ["ErrorAdjustingStock"] = "Error adjusting stock",
                ["SelectWarehouse"] = "Select Warehouse",
                ["CurrentStock"] = "Current Stock",
                ["MinimumQuantity"] = "Minimum Quantity",
                ["ReorderPoint"] = "Reorder Point",
                ["LastRestocked"] = "Last Restocked",
                ["LowStock"] = "Low Stock",
                ["InStock"] = "In Stock",
                ["OutOfStock"] = "Out of Stock",

                // Warehouses
                ["Warehouses"] = "Warehouses",
                ["Warehouse"] = "Warehouse",
                ["CreateWarehouse"] = "Create Warehouse",
                ["EditWarehouse"] = "Edit Warehouse",
                ["WarehouseName"] = "Warehouse Name",
                ["Default"] = "Default",
                ["DefaultWarehouse"] = "Default Warehouse",
                ["AllWarehouses"] = "All Warehouses",
                ["NoWarehousesFound"] = "No warehouses found",
                ["WarehouseNameRequired"] = "Warehouse name is required",
                ["WarehouseCreated"] = "Warehouse created successfully",
                ["WarehouseUpdated"] = "Warehouse updated successfully",
                ["WarehouseDeleted"] = "Warehouse deleted successfully",
                ["DeleteWarehouseConfirm"] = "Are you sure you want to delete this warehouse?",
                ["ErrorLoadingWarehouse"] = "Error loading warehouse",
                ["ErrorLoadingWarehouses"] = "Error loading warehouses",
                ["ErrorCreatingWarehouse"] = "Error creating warehouse",
                ["ErrorUpdatingWarehouse"] = "Error updating warehouse",
                ["ErrorDeletingWarehouse"] = "Error deleting warehouse",
                ["WarehouseNotFound"] = "Warehouse not found",

                // Individuals
                ["Individuals"] = "Individuals",
                ["Individual"] = "Individual",
                ["CreateIndividual"] = "Create Individual",
                ["EditIndividual"] = "Edit Individual",
                ["IndividualDetails"] = "Individual Details",
                ["FirstName"] = "First Name",
                ["LastName"] = "Last Name",
                ["FullName"] = "Full Name",
                ["IdentificationNumber"] = "Identification Number",
                ["AllIndividuals"] = "All Individuals",
                ["NoIndividualsFound"] = "No individuals found",
                ["FirstNameRequired"] = "First name is required",
                ["LastNameRequired"] = "Last name is required",
                ["IdentificationNumberRequired"] = "Identification number is required",
                ["IndividualCreated"] = "Individual created successfully",
                ["IndividualUpdated"] = "Individual updated successfully",
                ["IndividualDeleted"] = "Individual deleted successfully",
                ["DeleteIndividualConfirm"] = "Are you sure you want to delete this individual?",
                ["ErrorLoadingIndividual"] = "Error loading individual",
                ["ErrorLoadingIndividuals"] = "Error loading individuals",
                ["ErrorCreatingIndividual"] = "Error creating individual",
                ["ErrorUpdatingIndividual"] = "Error updating individual",
                ["ErrorDeletingIndividual"] = "Error deleting individual",
                ["IndividualNotFound"] = "Individual not found",
                ["ActiveIndividuals"] = "Active",
                ["InactiveIndividuals"] = "Inactive",
                ["ActiveIndividual"] = "Active",
                ["InactiveIndividual"] = "Inactive",

                // Purchase Notes
                ["PurchaseNotes"] = "Purchase Notes",
                ["PurchaseNote"] = "Purchase Note",
                ["CreatePurchaseNote"] = "Create Purchase Note",
                ["EditPurchaseNote"] = "Edit Purchase Note",
                ["PurchaseNoteDetails"] = "Purchase Note Details",
                ["NoteNumber"] = "Note Number",
                ["PurchaseDate"] = "Purchase Date",
                ["AllPurchaseNotes"] = "All Purchase Notes",
                ["NoPurchaseNotesFound"] = "No purchase notes found",
                ["MarkAsPaid"] = "Mark as Paid",
                ["MarkAsPaidQuestion"] = "Mark as Paid?",
                ["Completed"] = "Completed",
                ["Paid"] = "Paid",
                ["Unpaid"] = "Unpaid",
                ["PurchaseNoteCreated"] = "Purchase note created successfully",
                ["PurchaseNoteUpdated"] = "Purchase note updated successfully",
                ["PurchaseNoteDeleted"] = "Purchase note deleted successfully",
                ["PurchaseNoteMarkedPaid"] = "Purchase note marked as paid",
                ["DeletePurchaseNoteConfirm"] = "Are you sure you want to delete this purchase note?",
                ["ErrorLoadingPurchaseNote"] = "Error loading purchase note",
                ["ErrorLoadingPurchaseNotes"] = "Error loading purchase notes",
                ["ErrorCreatingPurchaseNote"] = "Error creating purchase note",
                ["ErrorUpdatingPurchaseNote"] = "Error updating purchase note",
                ["ErrorDeletingPurchaseNote"] = "Error deleting purchase note",
                ["PurchaseNoteNotFound"] = "Purchase note not found",
            },
            #endregion

            #region Macedonian translations
            ["mk"] = new Dictionary<string, string>
            {
                // Navigation
                ["Dashboard"] = "Почетна",
                ["Companies"] = "Компании",
                ["Invoices"] = "Фактури",
                ["Payments"] = "Плаќања",
                ["Settings"] = "Подесувања",
                ["Notifications"] = "Известувања",

                // Dashboard
                ["TotalDue"] = "Вкупно должење",
                ["TotalInvoices"] = "Вкупно фактури",
                ["Overdue"] = "Задоцнети",
                ["TotalPaid"] = "Вкупно платено",
                ["InvoicesUnpaid"] = "Неплатени фактури",
                ["Paid"] = "Платени",
                ["RequiresAttention"] = "Потребно внимание",
                ["AllTimeCollected"] = "Вкупно наплатено",
                ["RecentInvoices"] = "Последни фактури",
                ["NewInvoice"] = "Нова фактура",
                ["NoInvoicesFound"] = "Нема пронајдени фактури",
                ["InvoiceNumber"] = "Фактура #",
                ["Company"] = "Компанија",
                ["Amount"] = "Износ",
                ["Status"] = "Статус",
                ["DueDate"] = "Рок на плаќање",
                ["Actions"] = "Акции",
                ["ViewAllInvoices"] = "Погледни ги сите фактури",

                // Status
                ["Draft"] = "Нацрт",
                ["Sent"] = "Испратена",
                ["PartiallyPaid"] = "Делумно платена",
                ["PaidStatus"] = "Платена",
                ["OverdueStatus"] = "Задоцнета",
                ["Cancelled"] = "Откажана",

                // Common
                ["Loading"] = "Вчитување...",
                ["Saving"] = "Зачувување...",
                ["Save"] = "Зачувај",
                ["Cancel"] = "Откажи",
                ["Delete"] = "Избриши",
                ["Edit"] = "Измени",
                ["View"] = "Прегледај",
                ["Create"] = "Креирај",
                ["Update"] = "Ажурирај",
                ["Search"] = "Пребарај",
                ["Filter"] = "Филтрирај",
                ["Export"] = "Извези",
                ["Import"] = "Увези",
                ["InvoiceSystem"] = "Систем за фактури",
                ["Help"] = "Помош",
                ["Privacy"] = "Приватност",
                ["Terms"] = "Услови",
                ["Brajkovci"] = "Брајковци, Валандово, Македонија",
                ["ThankYou"] = "Ви благодариме за соработката!",
                ["AdvancedFilters"] = "Напредни филтери",
                ["AmountRange"] = "Опсег на износ",
                ["Min"] = "Мин",
                ["Max"] = "Макс",
                ["From"] = "Од",
                ["To"] = "До",
                ["ClearFilters"] = "Избриши филтери",
                ["NoItemsFound"] = "Нема пронајдени предмети",
                ["Previous"] = "Претходно",
                ["Next"] = "Следно",
                ["Page"] = "Страна",
                ["Of"] = "од",
                ["ItemsPerPage"] = "Предмети по страна:",

                // Email
                ["SendInvoice"] = "Испрати фактура",
                ["SendEmail"] = "Испрати е-пошта",
                ["EmailSent"] = "Е-поштата е успешно испратена",
                ["SendingEmail"] = "Испраќање на е-пошта...",
                ["EnterCustomMessage"] = "Внесете порака за да ја вклучите во е-поштата",
                ["EmailWillBeSent"] = "Фактурата ќе биде испратена како прилог и статусот ќе биде ажуриран на 'Испратена'",

                // Companies
                ["AllCompanies"] = "Сите компании",
                ["Clients"] = "Клиенти",
                ["Vendors"] = "Добавувачи",
                ["CreateCompany"] = "Креирај компанија",
                ["EditCompany"] = "Измени компанија",
                ["CompanyDetails"] = "Детали за компанија",
                ["BackToCompanies"] = "Назад кон компании",
                ["ContactPerson"] = "Контакт лице",
                ["Email"] = "Е-пошта",
                ["Phone"] = "Телефон",
                ["Address"] = "Адреса",
                ["TaxID"] = "Даночен број",
                ["CreditLimit"] = "Кредитен лимит",
                ["Active"] = "Активна",
                ["Inactive"] = "Неактивна",
                ["Client"] = "Клиент",
                ["Vendor"] = "Добавувач",
                ["ClientAndVendor"] = "Клиент и Добавувач",
                ["SelectCompanyType"] = "Избери тип на компанија",
                ["EnterCompanyName"] = "Внеси име на компанија",
                ["EnterContactPerson"] = "Внеси контакт лице",
                ["EnterEmail"] = "Внеси е-пошта",
                ["EnterPhone"] = "Внеси телефонски број",
                ["EnterAddress"] = "Внеси целосна адреса",
                ["EnterTaxID"] = "Внеси даночен број",
                ["EnterCreditLimit"] = "Внеси кредитен лимит",
                ["CompanyName"] = "Име на компанија",
                ["CompanyType"] = "Тип на компанија",
                ["CompanyCreated"] = "Компанијата е успешно креирана",
                ["CompanyUpdated"] = "Компанијата е успешно ажурирана",
                ["CompanyDeleted"] = "Компанијата е успешно избришана",
                ["ErrorLoadingCompany"] = "Грешка при вчитување на компанија",
                ["ErrorCreatingCompany"] = "Грешка при креирање на компанија",
                ["ErrorUpdatingCompany"] = "Грешка при ажурирање на компанија",
                ["ErrorDeletingCompany"] = "Грешка при бришење на компанија",
                ["DeleteCompanyConfirm"] = "Дали сте сигурни дека сакате да ја избришете оваа компанија? Ова дејство не може да се врати.",
                ["PleaseEnterCompanyName"] = "Ве молиме внесете име на компанија",
                ["PleaseEnterCompanyType"] = "Ве молиме внесете тип на компанија",
                ["BalanceOwed"] = "Салдо",
                ["WeOwe"] = "Ние должиме",
                ["TheyOwe"] = "Тие ни должат",
                ["NetBalance"] = "Нето салдо",
                ["ViewInvoices"] = "Прегледај фактури",
                ["TotalInvoicesCount"] = "Вкупно фактури",
                ["Settled"] = "Намирени",
                ["ChooseCompanyType"] = "Одбери тип на компанија",

                // Invoices
                ["Invoice"] = "Фактура",
                ["CreateInvoice"] = "Креирај фактура",
                ["EditInvoice"] = "Измени фактура",
                ["InvoiceDetails"] = "Детали за фактура",
                ["AllInvoices"] = "Сите фактури",
                ["Receivables"] = "Побарувања",
                ["Payables"] = "Обврски",
                ["Type"] = "Тип",
                ["IssueDate"] = "Датум на издавање",
                ["Notes"] = "Забелешки",
                ["LineItems"] = "Ставки",
                ["Description"] = "Опис",
                ["Quantity"] = "Количина",
                ["UnitPrice"] = "Единечна цена",
                ["TaxRate"] = "Даночна стапка",
                ["Total"] = "Вкупно",
                ["Subtotal"] = "Подзбир",
                ["Tax"] = "Данок",
                ["AmountPaid"] = "Платено",
                ["AmountDue"] = "За наплата",
                ["AddLineItem"] = "Додади ставка",
                ["RemoveLineItem"] = "Отстрани",
                ["BillTo"] = "Наплата на",
                ["BillFrom"] = "Наплата од",
                ["InvoiceInformation"] = "Информации за фактура",
                ["PaymentHistory"] = "Историја на плаќања",
                ["NoPaymentsRecorded"] = "Нема евидентирани плаќања",
                ["BackToInvoices"] = "Назад кон фактури",
                ["SelectCompany"] = "Избери компанија",
                ["SelectType"] = "Избери тип",
                ["Receivable"] = "Побарување",
                ["Payable"] = "Обврска",
                ["ConfirmDelete"] = "Потврди бришење",
                ["DeleteInvoiceConfirm"] = "Дали сте сигурни дека сакате да ја избришете оваа фактура? Ова дејство не може да се врати.",
                ["InvoiceDeleted"] = "Фактурата е успешно избришана",
                ["InvoiceCreated"] = "Фактурата е успешно креирана",
                ["InvoiceUpdated"] = "Фактурата е успешно ажурирана",
                ["ErrorLoadingInvoice"] = "Грешка при вчитување на фактура",
                ["ErrorCreatingInvoice"] = "Грешка при креирање на фактура",
                ["ErrorUpdatingInvoice"] = "Грешка при ажурирање на фактура",
                ["ErrorDeletingInvoice"] = "Грешка при бришење на фактура",
                ["PleaseAddLineItems"] = "Ве молиме додадете барем една ставка",
                ["PleaseEnterDescriptionOrSelectProduct"] = "Ве молиме внесете опис или изберете производ за секоја ставка",
                ["Yes"] = "Да",
                ["No"] = "Не",
                ["Close"] = "Затвори",
                ["PaymentDate"] = "Датум на плаќање",
                ["PaymentAmount"] = "Износ на плаќање",
                ["PaymentMethod"] = "Начин на плаќање",
                ["ReferenceNumber"] = "Референтен број",
                ["RecordedBy"] = "Евидентирано од",
                ["ShowingResults"] = "Прикажани {0} до {1} од {2} резултати",
                ["Days"] = "денови",
                ["SelectInvoiceType"] = "Избери тип на фактура",
                ["DaysFromIssue"] = "Денови од датум на издавање",
                ["CalculateDueDate"] = "Пресметај рок на плаќање",
                ["AddItem"] = "Додади ставка",
                ["RemoveItem"] = "Отстрани ставка",
                ["Item"] = "Ставка",
                ["PleaseSelectCompany"] = "Ве молиме изберете компанија",
                ["PleaseSelectType"] = "Ве молиме изберете тип на фактура",
                ["IssueDateRequired"] = "Потребен е датум на издавање",
                ["DueDateRequired"] = "Потребен е краен рок",
                ["StatusRequired"] = "Потребен е статус",
                ["PleaseAddAtLeastOneLineItem"] = "Ве молиме додадете барем една ставка",
                ["EnterDescription"] = "Внесете опис",
                ["EnterQuantity"] = "Внесете количина",
                ["EnterUnitPrice"] = "Внесете единечна цена",
                ["EnterTaxRate"] = "Внесете даночна стапка (%)",
                ["Bill"] = "Сметка",
                ["SendInvoiceEmail"] = "Испрати фактура преку е-пошта",
                ["RecipientEmail"] = "Е-пошта на примачот",
                ["EnterRecipientEmail"] = "Внеси ја е-поштата на примачот",
                ["IncludeCustomMessage"] = "Внеси дополнителна порака",
                ["CustomMessage"] = "Дополнителна порака",
                ["CustomMessageHelper"] = "По желба: Додадете лична порака што ќе биде вклучена во е-поштата",
                ["Sending"] = "Се испраќа...",
                ["InvalidEmailFormat"] = "Внесете важечка е-пошта",
                ["InvoiceEmailSentSuccessfully"] = "Фактурата е успешно испратена по е-пошта!",
                ["ErrorSendingEmail"] = "Се случи грешка при испраќањето е-пошта",

                // Payments
                ["Cash"] = "Готовина",
                ["Check"] = "Чек",
                ["BankTransfer"] = "Банкарски трансфер",
                ["CreditCard"] = "Кредитна картичка",
                ["DebitCard"] = "Дебитна картичка",
                ["Other"] = "Друго",
                ["AllPayments"] = "Сите плаќања",
                ["CreatePayment"] = "Креирај плаќање",
                ["RecordPayment"] = "Евидентирај плаќање",
                ["PaymentDetails"] = "Детали за плаќање",
                ["BackToPayments"] = "Назад кон плаќања",
                ["SelectInvoice"] = "Избери фактура",
                ["SelectPaymentMethod"] = "Избери начин на плаќање",
                ["PleaseSelectPaymentMethod"] = "Ве молиме изберете начин на плаќање",
                ["PaymentDateRequired"] = "Потребен е датум на плаќање",
                ["EnterAmount"] = "Внеси износ",
                ["EnterReferenceNumber"] = "Внеси референтен број",
                ["EnterNotes"] = "Внеси забелешки",
                ["MaximumAmount"] = "Максимален износ",
                ["RemainingBalance"] = "Преостанато салдо",
                ["InvoiceAmount"] = "Износ на фактура",
                ["AlreadyPaid"] = "Веќе платено",
                ["PaymentExceedsBalance"] = "Износот на плаќање го надминува преостанатото салдо",
                ["PleaseSelectInvoice"] = "Ве молиме изберете фактура",
                ["PleaseEnterAmount"] = "Ве молиме внесете износ на плаќање",
                ["PaymentCreated"] = "Плаќањето е успешно евидентирано",
                ["PaymentUpdated"] = "Плаќањето е успешно ажурирано",
                ["PaymentDeleted"] = "Плаќањето е успешно избришано",
                ["ErrorLoadingPayment"] = "Грешка при вчитување на плаќање",
                ["ErrorCreatingPayment"] = "Грешка при креирање на плаќање",
                ["ErrorUpdatingPayment"] = "Грешка при ажурирање на плаќање",
                ["ErrorDeletingPayment"] = "Грешка при бришење на плаќање",
                ["DeletePaymentConfirm"] = "Дали сте сигурни дека сакате да го избришете ова плаќање? Ова ќе го ажурира салдото на фактурата.",
                ["EditPayment"] = "Измени плаќање",
                ["NoPaymentsFound"] = "Нема пронајдени плаќања",
                ["CreatedAt"] = "Извршено на",
                ["Payment"] = "Плаќање",

                // Export
                ["ExportToExcel"] = "Извези во Excel",
                ["ExportForPrinting"] = "Извези за печатење",
                ["ExportAllInvoices"] = "Извези ги сите фактури",
                ["ExportByDateRange"] = "Извези по датум",
                ["StartDate"] = "Почетен датум",
                ["EndDate"] = "Краен датум",
                ["ExportInvoices"] = "Извези фактури",
                ["Exporting"] = "Извезување...",
                ["ExportSuccess"] = "Датотеката е успешно извезена",
                ["ExportError"] = "Грешка при извезување на датотека",

                // Products
                ["Products"] = "Производи",
                ["Product"] = "Производ",
                ["CreateProduct"] = "Креирај Производ",
                ["EditProduct"] = "Измени Производ",
                ["ProductDetails"] = "Детали за Производ",
                ["ProductName"] = "Име на Производ",
                ["ProductCode"] = "Шифра на Производ",
                ["Code"] = "Шифра",
                ["DefaultPrice"] = "Стандардна Цена",
                ["Price"] = "Цена",
                ["Unit"] = "Единица",
                ["UnitHelper"] = "пр. парче, кг, л, м",
                ["AllProducts"] = "Сите Производи",
                ["NoProductsFound"] = "Нема пронајдено производи",
                ["ViewStock"] = "Преглед на Залиха",
                ["CodeRequired"] = "Шифрата на производот е задолжителна",
                ["NameRequired"] = "Името на производот е задолжително",
                ["UnitRequired"] = "Единицата е задолжителна",
                ["PriceRequired"] = "Цената е задолжителна",
                ["ProductCreated"] = "Производот е успешно креиран",
                ["ProductUpdated"] = "Производот е успешно изменет",
                ["ProductDeleted"] = "Производот е успешно избришан",
                ["DeleteProductConfirm"] = "Дали сте сигурни дека сакате да го избришете овој производ?",
                ["ErrorLoadingProduct"] = "Грешка при вчитување на производот",
                ["ErrorLoadingProducts"] = "Грешка при вчитување на производите",
                ["ErrorCreatingProduct"] = "Грешка при креирање на производот",
                ["ErrorUpdatingProduct"] = "Грешка при изменување на производот",
                ["ErrorDeletingProduct"] = "Грешка при бришење на производот",
                ["ProductNotFound"] = "Производот не е пронајден",
                ["CustomDescription"] = "Сопствен Опис",
                ["OrEnterCustom"] = "Или внесете сопствен опис",
                ["SelectProduct"] = "Избери Производ",
                ["ActiveProducts"] = "Активни",
                ["InactiveProducts"] = "Неактивни",
                ["ProductActive"] = "Активен",
                ["ProductInactive"] = "Неактивен",

                // Inventory
                ["Inventory"] = "Залиха",
                ["Stock"] = "Залиха",
                ["StockLevel"] = "Ниво на Залиха",
                ["CurrentStock"] = "Тековна Залиха",
                ["MinimumQuantity"] = "Минимална Количина",
                ["ReorderPoint"] = "Точка за Нарачка",
                ["LastRestocked"] = "Последно Пополнување",
                ["LowStock"] = "Ниска Залиха",
                ["InStock"] = "На Залиха",
                ["OutOfStock"] = "Нема на Залиха",
                ["SelectWarehouse"] = "Избери Магацин",
                ["AdjustStock"] = "Прилагоди Залиха",
                ["Adjust"] = "Прилагоди",
                ["AdjustmentType"] = "Тип на прилагодување",
                ["IncreaseStock"] = "Додади",
                ["DecreaseStock"] = "Одземи",
                ["AdjustmentReason"] = "Причина",
                ["StockAdjusted"] = "Залихата е успешно прилагодена",
                ["ErrorAdjustingStock"] = "Грешка при прилагодување на залиха",

                // Warehouses
                ["Warehouses"] = "Магацини",
                ["Warehouse"] = "Магацин",
                ["CreateWarehouse"] = "Креирај Магацин",
                ["EditWarehouse"] = "Измени Магацин",
                ["WarehouseName"] = "Име на Магацин",
                ["Default"] = "Стандардно",
                ["DefaultWarehouse"] = "Стандарден Магацин",
                ["AllWarehouses"] = "Сите Магацини",
                ["NoWarehousesFound"] = "Нема пронајдено магацини",
                ["WarehouseNameRequired"] = "Името на магацинот е задолжително",
                ["WarehouseCreated"] = "Магацинот е успешно креиран",
                ["WarehouseUpdated"] = "Магацинот е успешно изменет",
                ["WarehouseDeleted"] = "Магацинот е успешно избришан",
                ["DeleteWarehouseConfirm"] = "Дали сте сигурни дека сакате да го избришете овој магацин?",
                ["ErrorLoadingWarehouse"] = "Грешка при вчитување на магацинот",
                ["ErrorLoadingWarehouses"] = "Грешка при вчитување на магацините",
                ["ErrorCreatingWarehouse"] = "Грешка при креирање на магацинот",
                ["ErrorUpdatingWarehouse"] = "Грешка при изменување на магацинот",
                ["ErrorDeletingWarehouse"] = "Грешка при бришење на магацинот",
                ["WarehouseNotFound"] = "Магацинот не е пронајден",

                // Individuals
                ["Individuals"] = "Физички Лица",
                ["Individual"] = "Физичко Лице",
                ["CreateIndividual"] = "Креирај Физичко Лице",
                ["EditIndividual"] = "Измени Физичко Лице",
                ["IndividualDetails"] = "Детали за Физичко Лице",
                ["FirstName"] = "Име",
                ["LastName"] = "Презиме",
                ["FullName"] = "Име и Презиме",
                ["IdentificationNumber"] = "ЕМБГ",
                ["AllIndividuals"] = "Сите Физички Лица",
                ["NoIndividualsFound"] = "Нема пронајдено физички лица",
                ["FirstNameRequired"] = "Името е задолжително",
                ["LastNameRequired"] = "Презимето е задолжително",
                ["IdentificationNumberRequired"] = "ЕМБГ е задолжителен",
                ["IndividualCreated"] = "Физичкото лице е успешно креирано",
                ["IndividualUpdated"] = "Физичкото лице е успешно изменето",
                ["IndividualDeleted"] = "Физичкото лице е успешно избришано",
                ["DeleteIndividualConfirm"] = "Дали сте сигурни дека сакате да го избришете ова физичко лице?",
                ["ErrorLoadingIndividual"] = "Грешка при вчитување на физичкото лице",
                ["ErrorLoadingIndividuals"] = "Грешка при вчитување на физичките лица",
                ["ErrorCreatingIndividual"] = "Грешка при креирање на физичкото лице",
                ["ErrorUpdatingIndividual"] = "Грешка при изменување на физичкото лице",
                ["ErrorDeletingIndividual"] = "Грешка при бришење на физичкото лице",
                ["IndividualNotFound"] = "Физичкото лице не е пронајдено",
                ["ActiveIndividuals"] = "Активни",
                ["InactiveIndividuals"] = "Неактивни",
                ["ActiveIndividual"] = "Активен",
                ["InactiveIndividual"] = "Неактивен",

                // Purchase Notes
                ["PurchaseNotes"] = "Откупни Белешки",
                ["PurchaseNote"] = "Откупна Белешка",
                ["CreatePurchaseNote"] = "Креирај Откупна Белешка",
                ["EditPurchaseNote"] = "Измени Откупна Белешка",
                ["PurchaseNoteDetails"] = "Детали за Откупна Белешка",
                ["NoteNumber"] = "Број на Белешка",
                ["PurchaseDate"] = "Датум на Откуп",
                ["AllPurchaseNotes"] = "Сите Откупни Белешки",
                ["NoPurchaseNotesFound"] = "Нема пронајдено откупни белешки",
                ["MarkAsPaid"] = "Означи како Платено",
                ["MarkAsPaidQuestion"] = "Означи како Платено?",
                ["Completed"] = "Завршено",
                ["Paid"] = "Платено",
                ["Unpaid"] = "Неплатено",
                ["PurchaseNoteCreated"] = "Откупната белешка е успешно креирана",
                ["PurchaseNoteUpdated"] = "Откупната белешка е успешно изменета",
                ["PurchaseNoteDeleted"] = "Откупната белешка е успешно избришана",
                ["PurchaseNoteMarkedPaid"] = "Откупната белешка е означена како платена",
                ["DeletePurchaseNoteConfirm"] = "Дали сте сигурни дека сакате да ја избришете оваа откупна белешка?",
                ["ErrorLoadingPurchaseNote"] = "Грешка при вчитување на откупната белешка",
                ["ErrorLoadingPurchaseNotes"] = "Грешка при вчитување на откупните белешки",
                ["ErrorCreatingPurchaseNote"] = "Грешка при креирање на откупната белешка",
                ["ErrorUpdatingPurchaseNote"] = "Грешка при изменување на откупната белешка",
                ["ErrorDeletingPurchaseNote"] = "Грешка при бришење на откупната белешка",
                ["PurchaseNoteNotFound"] = "Откупната белешка не е пронајдена",
            }
            #endregion
        };

        public void SetLanguage(string language)
        {
            if (language != "en" && language != "mk")
                language = "mk";

            CultureInfo culture = new($"{language}-{language.ToUpper()}");

            culture.NumberFormat.CurrencySymbol = "MKD";
            culture.NumberFormat.CurrencyDecimalDigits = 2;
            culture.NumberFormat.CurrencyPositivePattern = 3;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;

            _currentLanguage = language;
            OnLanguageChanged?.Invoke();
        }

        public string GetString(string key)
        {
            if (_translations.TryGetValue(_currentLanguage, out Dictionary<string, string>? languageDict) && languageDict.TryGetValue(key, out string? value))
            {
                return value;
            }

            return key;
        }
    }
}
