namespace WarehouseInvoiceSystem.Application.Services
{
    using System.Globalization;
    using WarehouseInvoiceSystem.Application.Interfaces;

    public class LocalizationService : ILocalizationService
    {
        private string _currentLanguage = "mk";

        public string CurrentLanguage => _currentLanguage;

        public event Action? OnLanguageChanged;

        private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            #region English translations
            ["en"] = new Dictionary<string, string>
            {
                // Navigation
                ["Dashboard"] = "Dashboard",
                ["Companies"] = "Companies",
                ["Invoices"] = "Invoices",
                ["Payments"] = "Payments",
                ["Settings"] = "Settings",
                ["Notifications"] = "Notifications",

                // Dashboard
                ["TotalDue"] = "Total Due",
                ["TotalInvoices"] = "Total Invoices",
                ["Overdue"] = "Overdue",
                ["TotalPaid"] = "Total Paid",
                ["InvoicesUnpaid"] = "invoices unpaid",
                ["Paid"] = "paid",
                ["RequiresAttention"] = "Requires attention",
                ["AllTimeCollected"] = "All time collected",
                ["RecentInvoices"] = "Recent Invoices",
                ["NewInvoice"] = "New Invoice",
                ["NoInvoicesFound"] = "No invoices found",
                ["InvoiceNumber"] = "Invoice #",
                ["Company"] = "Company",
                ["Amount"] = "Amount",
                ["Status"] = "Status",
                ["DueDate"] = "Due Date",
                ["Actions"] = "Actions",
                ["ViewAllInvoices"] = "View All Invoices",

                // Status
                ["Draft"] = "Draft",
                ["Sent"] = "Sent",
                ["PartiallyPaid"] = "Partially Paid",
                ["PaidStatus"] = "Paid",
                ["OverdueStatus"] = "Overdue",
                ["Cancelled"] = "Cancelled",

                // Common
                ["Loading"] = "Loading...",
                ["Save"] = "Save",
                ["Cancel"] = "Cancel",
                ["Delete"] = "Delete",
                ["Edit"] = "Edit",
                ["View"] = "View",
                ["Create"] = "Create",
                ["Update"] = "Update",
                ["Search"] = "Search",
                ["Filter"] = "Filter",
                ["Export"] = "Export",
                ["Import"] = "Import",
                ["InvoiceSystem"] = "Invoice System",
                ["Help"] = "Help",
                ["Privacy"] = "Privacy",
                ["Terms"] = "Terms",
                ["Brajkovci"] = "Brajkovci, Valandovo, Makedonija",
                ["ThankYou"] = "Thank you for your business!",

                // Email
                ["SendInvoice"] = "Send Invoice",
                ["SendEmail"] = "Send Email",
                ["RecipientEmail"] = "Recipient Email",
                ["CustomMessage"] = "Custom Message (Optional)",
                ["EmailSent"] = "Email sent successfully",
                ["ErrorSendingEmail"] = "Error sending email",
                ["SendingEmail"] = "Sending email...",
                ["EnterRecipientEmail"] = "Enter recipient email address",
                ["EnterCustomMessage"] = "Enter a custom message to include in the email",
                ["EmailWillBeSent"] = "The invoice will be sent as an attachment and the status will be updated to 'Sent'",

                // Companies
                ["AllCompanies"] = "All Companies",
                ["Clients"] = "Clients",
                ["Vendors"] = "Vendors",
                ["CreateCompany"] = "Create Company",
                ["EditCompany"] = "Edit Company",
                ["CompanyDetails"] = "Company Details",
                ["BackToCompanies"] = "Back to Companies",
                ["ContactPerson"] = "Contact Person",
                ["Email"] = "Email",
                ["Phone"] = "Phone",
                ["Address"] = "Address",
                ["TaxID"] = "Tax ID",
                ["CreditLimit"] = "Credit Limit",
                ["Active"] = "Active",
                ["Inactive"] = "Inactive",
                ["Client"] = "Client",
                ["Vendor"] = "Vendor",
                ["ClientAndVendor"] = "Client & Vendor",
                ["SelectCompanyType"] = "Select company type",
                ["EnterCompanyName"] = "Enter company name",
                ["EnterContactPerson"] = "Enter contact person",
                ["EnterEmail"] = "Enter email address",
                ["EnterPhone"] = "Enter phone number",
                ["EnterAddress"] = "Enter full address",
                ["EnterTaxID"] = "Enter tax ID",
                ["EnterCreditLimit"] = "Enter credit limit",
                ["CompanyName"] = "Company Name",
                ["CompanyType"] = "Company Type",
                ["CompanyCreated"] = "Company created successfully",
                ["CompanyUpdated"] = "Company updated successfully",
                ["CompanyDeleted"] = "Company deleted successfully",
                ["ErrorLoadingCompany"] = "Error loading company",
                ["ErrorCreatingCompany"] = "Error creating company",
                ["ErrorUpdatingCompany"] = "Error updating company",
                ["ErrorDeletingCompany"] = "Error deleting company",
                ["DeleteCompanyConfirm"] = "Are you sure you want to delete this company? This action cannot be undone.",
                ["PleaseEnterCompanyName"] = "Please enter company name",
                ["BalanceOwed"] = "Balance Owed",
                ["WeOwe"] = "We Owe",
                ["TheyOwe"] = "They Owe Us",
                ["NetBalance"] = "Net Balance",
                ["ViewInvoices"] = "View Invoices",
                ["TotalInvoicesCount"] = "Total Invoices",

                // Invoices
                ["Invoice"] = "Invoice",
                ["CreateInvoice"] = "Create Invoice",
                ["EditInvoice"] = "Edit Invoice",
                ["InvoiceDetails"] = "Invoice Details",
                ["AllInvoices"] = "All Invoices",
                ["Receivables"] = "Receivables",
                ["Payables"] = "Payables",
                ["Type"] = "Type",
                ["IssueDate"] = "Issue Date",
                ["Notes"] = "Notes",
                ["LineItems"] = "Line Items",
                ["Description"] = "Description",
                ["Quantity"] = "Quantity",
                ["UnitPrice"] = "Unit Price",
                ["TaxRate"] = "Tax Rate",
                ["Total"] = "Total",
                ["Subtotal"] = "Subtotal",
                ["Tax"] = "Tax",
                ["AmountPaid"] = "Amount Paid",
                ["AmountDue"] = "Amount Due",
                ["AddLineItem"] = "Add Line Item",
                ["RemoveLineItem"] = "Remove",
                ["BillTo"] = "Bill To",
                ["BillFrom"] = "Bill From",
                ["InvoiceInformation"] = "Invoice Information",
                ["PaymentHistory"] = "Payment History",
                ["RecordPayment"] = "Record Payment",
                ["NoPaymentsRecorded"] = "No payments recorded yet",
                ["BackToInvoices"] = "Back to Invoices",
                ["SelectCompany"] = "Select Company",
                ["SelectType"] = "Select Type",
                ["Receivable"] = "Receivable",
                ["Payable"] = "Payable",
                ["ConfirmDelete"] = "Confirm Delete",
                ["DeleteInvoiceConfirm"] = "Are you sure you want to delete this invoice? This action cannot be undone.",
                ["InvoiceDeleted"] = "Invoice deleted successfully",
                ["InvoiceCreated"] = "Invoice created successfully",
                ["InvoiceUpdated"] = "Invoice updated successfully",
                ["ErrorLoadingInvoice"] = "Error loading invoice",
                ["ErrorCreatingInvoice"] = "Error creating invoice",
                ["ErrorUpdatingInvoice"] = "Error updating invoice",
                ["ErrorDeletingInvoice"] = "Error deleting invoice",
                ["PleaseAddLineItems"] = "Please add at least one line item",
                ["Yes"] = "Yes",
                ["No"] = "No",
                ["Close"] = "Close",
                ["PaymentDate"] = "Payment Date",
                ["PaymentAmount"] = "Payment Amount",
                ["PaymentMethod"] = "Payment Method",
                ["ReferenceNumber"] = "Reference Number",
                ["RecordedBy"] = "Recorded By",
                ["ShowingResults"] = "Showing {0} to {1} of {2} results",
                ["Days"] = "days",
                ["SelectInvoiceType"] = "Select Invoice Type",
                ["DaysFromIssue"] = "Days from issue date",
                ["CalculateDueDate"] = "Calculate Due Date",
                ["AddItem"] = "Add Item",
                ["RemoveItem"] = "Remove Item",
                ["Item"] = "Item",
                ["PleaseSelectCompany"] = "Please select a company",
                ["PleaseSelectType"] = "Please select invoice type",
                ["PleaseAddAtLeastOneLineItem"] = "Please add at least one line item",
                ["EnterDescription"] = "Enter description",
                ["EnterQuantity"] = "Enter quantity",
                ["EnterUnitPrice"] = "Enter unit price",
                ["EnterTaxRate"] = "Enter tax rate (%)",
                ["Bill"] = "Bill",
                ["SendEmail"] = "Send Invoice Email",
                ["SendInvoiceEmail"] = "Send Invoice via Email",
                ["RecipientEmail"] = "Recipient Email",
                ["EnterRecipientEmail"] = "Enter the recipient's email address",
                ["IncludeCustomMessage"] = "Include a custom message",
                ["CustomMessage"] = "Custom Message",
                ["CustomMessageHelper"] = "Optional: Add a personal note to include in the email",
                ["Sending"] = "Sending...",
                ["InvalidEmailFormat"] = "Please enter a valid email address",
                ["InvoiceEmailSentSuccessfully"] = "Invoice email sent successfully!",
                ["ErrorSendingEmail"] = "Error sending email",

                // Payments
                ["Cash"] = "Cash",
                ["Check"] = "Check",
                ["BankTransfer"] = "Bank Transfer",
                ["CreditCard"] = "Credit Card",
                ["DebitCard"] = "Debit Card",
                ["Other"] = "Other",
                ["AllPayments"] = "All Payments",
                ["CreatePayment"] = "Create Payment",
                ["RecordPayment"] = "Record Payment",
                ["PaymentDetails"] = "Payment Details",
                ["BackToPayments"] = "Back to Payments",
                ["SelectInvoice"] = "Select Invoice",
                ["SelectPaymentMethod"] = "Select payment method",
                ["EnterAmount"] = "Enter amount",
                ["EnterReferenceNumber"] = "Enter reference number",
                ["EnterNotes"] = "Enter notes",
                ["MaximumAmount"] = "Maximum amount",
                ["RemainingBalance"] = "Remaining Balance",
                ["InvoiceAmount"] = "Invoice Amount",
                ["AlreadyPaid"] = "Already Paid",
                ["PaymentExceedsBalance"] = "Payment amount exceeds remaining balance",
                ["PleaseSelectInvoice"] = "Please select an invoice",
                ["PleaseEnterAmount"] = "Please enter payment amount",
                ["PaymentCreated"] = "Payment recorded successfully",
                ["PaymentUpdated"] = "Payment updated successfully",
                ["PaymentDeleted"] = "Payment deleted successfully",
                ["ErrorLoadingPayment"] = "Error loading payment",
                ["ErrorCreatingPayment"] = "Error creating payment",
                ["ErrorUpdatingPayment"] = "Error updating payment",
                ["ErrorDeletingPayment"] = "Error deleting payment",
                ["DeletePaymentConfirm"] = "Are you sure you want to delete this payment? This will update the invoice balance.",
                ["EditPayment"] = "Edit Payment",
                ["NoPaymentsFound"] = "No payments found",

                // Export
                ["ExportToExcel"] = "Export to Excel",
                ["ExportForPrinting"] = "Export for Printing",
                ["ExportAllInvoices"] = "Export All Invoices",
                ["ExportByDateRange"] = "Export by Date Range",
                ["StartDate"] = "Start Date",
                ["EndDate"] = "End Date",
                ["ExportInvoices"] = "Export Invoices",
                ["Exporting"] = "Exporting...",
                ["ExportSuccess"] = "File exported successfully",
                ["ExportError"] = "Error exporting file",
            },
            #endregion

            #region Macedonian translations
            ["mk"] = new Dictionary<string, string>
            {
                // Navigation
                ["Dashboard"] = "Почетна",
                ["Companies"] = "Компании",
                ["Invoices"] = "Фактури",
                ["Payments"] = "Плаќања",
                ["Settings"] = "Подесувања",
                ["Notifications"] = "Известувања",

                // Dashboard
                ["TotalDue"] = "Вкупно должење",
                ["TotalInvoices"] = "Вкупно фактури",
                ["Overdue"] = "Задоцнети",
                ["TotalPaid"] = "Вкупно платено",
                ["InvoicesUnpaid"] = "Неплатени фактури",
                ["Paid"] = "Платени",
                ["RequiresAttention"] = "Потребно внимание",
                ["AllTimeCollected"] = "Вкупно наплатено",
                ["RecentInvoices"] = "Последни фактури",
                ["NewInvoice"] = "Нова фактура",
                ["NoInvoicesFound"] = "Нема пронајдени фактури",
                ["InvoiceNumber"] = "Фактура #",
                ["Company"] = "Компанија",
                ["Amount"] = "Износ",
                ["Status"] = "Статус",
                ["DueDate"] = "Рок на плаќање",
                ["Actions"] = "Акции",
                ["ViewAllInvoices"] = "Погледни ги сите фактури",

                // Status
                ["Draft"] = "Нацрт",
                ["Sent"] = "Испратена",
                ["PartiallyPaid"] = "Делумно платена",
                ["PaidStatus"] = "Платена",
                ["OverdueStatus"] = "Задоцнета",
                ["Cancelled"] = "Откажана",

                // Common
                ["Loading"] = "Вчитување...",
                ["Save"] = "Зачувај",
                ["Cancel"] = "Откажи",
                ["Delete"] = "Избриши",
                ["Edit"] = "Измени",
                ["View"] = "Прегледај",
                ["Create"] = "Креирај",
                ["Update"] = "Ажурирај",
                ["Search"] = "Пребарај",
                ["Filter"] = "Филтрирај",
                ["Export"] = "Извези",
                ["Import"] = "Увези",
                ["InvoiceSystem"] = "Систем за фактури",
                ["Help"] = "Помош",
                ["Privacy"] = "Приватност",
                ["Terms"] = "Услови",
                ["Brajkovci"] = "Брајковци, Валандово, Македонија",
                ["ThankYou"] = "Ви благодариме за соработката!",

                // Email
                ["SendInvoice"] = "Испрати фактура",
                ["SendEmail"] = "Испрати е-пошта",
                ["RecipientEmail"] = "Примач на е-пошта",
                ["CustomMessage"] = "Порака (Опционално)",
                ["EmailSent"] = "Е-поштата е успешно испратена",
                ["ErrorSendingEmail"] = "Грешка при испраќање на е-пошта",
                ["SendingEmail"] = "Испраќање на е-пошта...",
                ["EnterRecipientEmail"] = "Внесете адреса на примач",
                ["EnterCustomMessage"] = "Внесете порака за да ја вклучите во е-поштата",
                ["EmailWillBeSent"] = "Фактурата ќе биде испратена како прилог и статусот ќе биде ажуриран на 'Испратена'",

                // Companies
                ["AllCompanies"] = "Сите компании",
                ["Clients"] = "Клиенти",
                ["Vendors"] = "Добавувачи",
                ["CreateCompany"] = "Креирај компанија",
                ["EditCompany"] = "Измени компанија",
                ["CompanyDetails"] = "Детали за компанија",
                ["BackToCompanies"] = "Назад кон компании",
                ["ContactPerson"] = "Контакт лице",
                ["Email"] = "Е-пошта",
                ["Phone"] = "Телефон",
                ["Address"] = "Адреса",
                ["TaxID"] = "Даночен број",
                ["CreditLimit"] = "Кредитен лимит",
                ["Active"] = "Активна",
                ["Inactive"] = "Неактивна",
                ["Client"] = "Клиент",
                ["Vendor"] = "Добавувач",
                ["ClientAndVendor"] = "Клиент и Добавувач",
                ["SelectCompanyType"] = "Избери тип на компанија",
                ["EnterCompanyName"] = "Внеси име на компанија",
                ["EnterContactPerson"] = "Внеси контакт лице",
                ["EnterEmail"] = "Внеси е-пошта",
                ["EnterPhone"] = "Внеси телефонски број",
                ["EnterAddress"] = "Внеси целосна адреса",
                ["EnterTaxID"] = "Внеси даночен број",
                ["EnterCreditLimit"] = "Внеси кредитен лимит",
                ["CompanyName"] = "Име на компанија",
                ["CompanyType"] = "Тип на компанија",
                ["CompanyCreated"] = "Компанијата е успешно креирана",
                ["CompanyUpdated"] = "Компанијата е успешно ажурирана",
                ["CompanyDeleted"] = "Компанијата е успешно избришана",
                ["ErrorLoadingCompany"] = "Грешка при вчитување на компанија",
                ["ErrorCreatingCompany"] = "Грешка при креирање на компанија",
                ["ErrorUpdatingCompany"] = "Грешка при ажурирање на компанија",
                ["ErrorDeletingCompany"] = "Грешка при бришење на компанија",
                ["DeleteCompanyConfirm"] = "Дали сте сигурни дека сакате да ја избришете оваа компанија? Ова дејство не може да се врати.",
                ["PleaseEnterCompanyName"] = "Ве молиме внесете име на компанија",
                ["BalanceOwed"] = "Салдо",
                ["WeOwe"] = "Ние должиме",
                ["TheyOwe"] = "Тие ни должат",
                ["NetBalance"] = "Нето салдо",
                ["ViewInvoices"] = "Прегледај фактури",
                ["TotalInvoicesCount"] = "Вкупно фактури",

                // Invoices
                ["Invoice"] = "Фактура",
                ["CreateInvoice"] = "Креирај фактура",
                ["EditInvoice"] = "Измени фактура",
                ["InvoiceDetails"] = "Детали за фактура",
                ["AllInvoices"] = "Сите фактури",
                ["Receivables"] = "Побарувања",
                ["Payables"] = "Обврски",
                ["Type"] = "Тип",
                ["IssueDate"] = "Датум на издавање",
                ["Notes"] = "Забелешки",
                ["LineItems"] = "Ставки",
                ["Description"] = "Опис",
                ["Quantity"] = "Количина",
                ["UnitPrice"] = "Единечна цена",
                ["TaxRate"] = "Даночна стапка",
                ["Total"] = "Вкупно",
                ["Subtotal"] = "Подзбир",
                ["Tax"] = "Данок",
                ["AmountPaid"] = "Платено",
                ["AmountDue"] = "За наплата",
                ["AddLineItem"] = "Додади ставка",
                ["RemoveLineItem"] = "Отстрани",
                ["BillTo"] = "Наплата на",
                ["BillFrom"] = "Наплата од",
                ["InvoiceInformation"] = "Информации за фактура",
                ["PaymentHistory"] = "Историја на плаќања",
                ["RecordPayment"] = "Евидентирај плаќање",
                ["NoPaymentsRecorded"] = "Нема евидентирани плаќања",
                ["BackToInvoices"] = "Назад кон фактури",
                ["SelectCompany"] = "Избери компанија",
                ["SelectType"] = "Избери тип",
                ["Receivable"] = "Побарување",
                ["Payable"] = "Обврска",
                ["ConfirmDelete"] = "Потврди бришење",
                ["DeleteInvoiceConfirm"] = "Дали сте сигурни дека сакате да ја избришете оваа фактура? Ова дејство не може да се врати.",
                ["InvoiceDeleted"] = "Фактурата е успешно избришана",
                ["InvoiceCreated"] = "Фактурата е успешно креирана",
                ["InvoiceUpdated"] = "Фактурата е успешно ажурирана",
                ["ErrorLoadingInvoice"] = "Грешка при вчитување на фактура",
                ["ErrorCreatingInvoice"] = "Грешка при креирање на фактура",
                ["ErrorUpdatingInvoice"] = "Грешка при ажурирање на фактура",
                ["ErrorDeletingInvoice"] = "Грешка при бришење на фактура",
                ["PleaseAddLineItems"] = "Ве молиме додадете барем една ставка",
                ["Yes"] = "Да",
                ["No"] = "Не",
                ["Close"] = "Затвори",
                ["PaymentDate"] = "Датум на плаќање",
                ["PaymentAmount"] = "Износ на плаќање",
                ["PaymentMethod"] = "Начин на плаќање",
                ["ReferenceNumber"] = "Референтен број",
                ["RecordedBy"] = "Евидентирано од",
                ["ShowingResults"] = "Прикажани {0} до {1} од {2} резултати",
                ["Days"] = "денови",
                ["SelectInvoiceType"] = "Избери тип на фактура",
                ["DaysFromIssue"] = "Денови од датум на издавање",
                ["CalculateDueDate"] = "Пресметај рок на плаќање",
                ["AddItem"] = "Додади ставка",
                ["RemoveItem"] = "Отстрани ставка",
                ["Item"] = "Ставка",
                ["PleaseSelectCompany"] = "Ве молиме изберете компанија",
                ["PleaseSelectType"] = "Ве молиме изберете тип на фактура",
                ["PleaseAddAtLeastOneLineItem"] = "Ве молиме додадете барем една ставка",
                ["EnterDescription"] = "Внесете опис",
                ["EnterQuantity"] = "Внесете количина",
                ["EnterUnitPrice"] = "Внесете единечна цена",
                ["EnterTaxRate"] = "Внесете даночна стапка (%)",
                ["Bill"] = "Сметка",
                ["SendInvoiceEmail"] = "Испрати фактура преку е-пошта",
                ["RecipientEmail"] = "Е-пошта на примачот",
                ["EnterRecipientEmail"] = "Внеси ја е-поштата на примачот",
                ["IncludeCustomMessage"] = "Внеси дополнителна порака",
                ["CustomMessage"] = "Дополнителна порака",
                ["CustomMessageHelper"] = "По желба: Додадете лична порака што ќе биде вклучена во е-поштата",
                ["Sending"] = "Се испраќа...",
                ["InvalidEmailFormat"] = "Внесете важечка е-пошта",
                ["InvoiceEmailSentSuccessfully"] = "Фактурата е успешно испратена по е-пошта!",
                ["ErrorSendingEmail"] = "Се случи грешка при испраќањето е-пошта",

                // Payments
                ["Cash"] = "Готовина",
                ["Check"] = "Чек",
                ["BankTransfer"] = "Банкарски трансфер",
                ["CreditCard"] = "Кредитна картичка",
                ["DebitCard"] = "Дебитна картичка",
                ["Other"] = "Друго",
                ["AllPayments"] = "Сите плаќања",
                ["CreatePayment"] = "Креирај плаќање",
                ["RecordPayment"] = "Евидентирај плаќање",
                ["PaymentDetails"] = "Детали за плаќање",
                ["BackToPayments"] = "Назад кон плаќања",
                ["SelectInvoice"] = "Избери фактура",
                ["SelectPaymentMethod"] = "Избери начин на плаќање",
                ["EnterAmount"] = "Внеси износ",
                ["EnterReferenceNumber"] = "Внеси референтен број",
                ["EnterNotes"] = "Внеси забелешки",
                ["MaximumAmount"] = "Максимален износ",
                ["RemainingBalance"] = "Преостанато салдо",
                ["InvoiceAmount"] = "Износ на фактура",
                ["AlreadyPaid"] = "Веќе платено",
                ["PaymentExceedsBalance"] = "Износот на плаќање го надминува преостанатото салдо",
                ["PleaseSelectInvoice"] = "Ве молиме изберете фактура",
                ["PleaseEnterAmount"] = "Ве молиме внесете износ на плаќање",
                ["PaymentCreated"] = "Плаќањето е успешно евидентирано",
                ["PaymentUpdated"] = "Плаќањето е успешно ажурирано",
                ["PaymentDeleted"] = "Плаќањето е успешно избришано",
                ["ErrorLoadingPayment"] = "Грешка при вчитување на плаќање",
                ["ErrorCreatingPayment"] = "Грешка при креирање на плаќање",
                ["ErrorUpdatingPayment"] = "Грешка при ажурирање на плаќање",
                ["ErrorDeletingPayment"] = "Грешка при бришење на плаќање",
                ["DeletePaymentConfirm"] = "Дали сте сигурни дека сакате да го избришете ова плаќање? Ова ќе го ажурира салдото на фактурата.",
                ["EditPayment"] = "Измени плаќање",
                ["NoPaymentsFound"] = "Нема пронајдени плаќања",

                // Export
                ["ExportToExcel"] = "Извези во Excel",
                ["ExportForPrinting"] = "Извези за печатење",
                ["ExportAllInvoices"] = "Извези ги сите фактури",
                ["ExportByDateRange"] = "Извези по датум",
                ["StartDate"] = "Почетен датум",
                ["EndDate"] = "Краен датум",
                ["ExportInvoices"] = "Извези фактури",
                ["Exporting"] = "Извезување...",
                ["ExportSuccess"] = "Датотеката е успешно извезена",
                ["ExportError"] = "Грешка при извезување на датотека",
            }
            #endregion
        };

        public void SetLanguage(string language)
        {
            if (language != "en" && language != "mk")
                language = "mk";

            CultureInfo culture = new($"{language}-{language.ToUpper()}");

            culture.NumberFormat.CurrencySymbol = "MKD";
            culture.NumberFormat.CurrencyDecimalDigits = 2;
            culture.NumberFormat.CurrencyPositivePattern = 3;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;

            _currentLanguage = language;
            OnLanguageChanged?.Invoke();
        }

        public string GetString(string key)
        {
            if (_translations.TryGetValue(_currentLanguage, out Dictionary<string, string>? languageDict) && languageDict.TryGetValue(key, out string? value))
            {
                return value;
            }

            return key;
        }
    }
}
